### ISSUE TITLE
How to set defaults vars ?

### ISSUE THREAD

**Issue by oemden** [linuxhq/ansible-collection-cloudflare#6]
Hello, 
pardon my question as I'm pretty new to ansible, but I can't figure how to set variables for thisProle.

here is the project tree:

```
├── ansible.cfg
├── ansible.log
├── group_vars
│   └── all.yml
├── inventory
│   └── hosts
├── playbooks
│   ├── cloudflare-gather-infos.yml
└── requirements.yml
```

I've set variables in `group_vars/all` all and I even specify the pat in the playbook ( as it did not took it into account )

`group_vars/all.yml`:
```
cf_account_name: myAccount
cf_auth_token: MyToken123
```

`playbook: cloudflare-gather-infos.yml`:
```
---
- name: Get Cloudflare Informations
  hosts: localhost
  # become: true
  connection: local
  vars_files:
    - ../group_vars/all.yml

  pre_tasks:
  - name: test role variables explicitly
    set_fact:
      cf_account_name: "{{ cf_account_name }}"
      cf_auth_token: "{{ cf_auth_token }}"

  tasks:
    - name: Print variables
      debug:
        msg: 
          - "cf_account_name = {{ cf_account_name | default('NOT DEFINED') }}"
          - "cf_auth_token = {{ cf_auth_token | default('NOT DEFINED') }}"

  roles:
    # Gather information about cloudflare account
    - role: linuxhq.cloudflare.account_info
      cf_account_name: "{{ cf_account_name }}"
      cf_auth_token: "{{ cf_auth_token }}"

```

If I comment the role and only use `tasks` ( and/or `pre_tasks` ), the vars are found with no issues:

```
ansible-playbook playbooks/cloudflare-gather-infos.yml -v
Using /path/to/cloudflare-ansible/ansible.cfg as config file

PLAY [Get Cloudflare Informations] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test role variables explicitly] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"cf_account_name": "myAccount", "cf_auth_token": "MyToken123"}, "changed": false}

TASK [Print variables] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "cf_account_name = myAccount",
        "cf_auth_token = MyToken123"
    ]
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

so far so good, but when enabling a role, it miserably fails:

```
playbooks/cloudflare-gather-infos.yml -v
Using /Users/oem/dev/oemden/cloudflare-ansible/ansible.cfg as config file

PLAY [Get Cloudflare Informations] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test role variables explicitly] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"cf_account_name": "myAccount", "cf_auth_token": "MyToken123"}, "changed": false}

TASK [linuxhq.cloudflare.account_info : Ensure cloudflare account details are gathered] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'cf_account_name is not none' failed. The error was: An unhandled exception occurred while templating '{{ cf_account_name }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ cf_account_name }}'.
```

The only way I got it working is hardcoding account and Token in the Playbook which is not imaginable` in a versioned controlled project.

it may be right in front of me, but I can not figure it out

**Comment by tkimball83** [comment]
Hey @oemden, welcome to ansible!

So, to begin I would recommend staying away from using `var_files` unless absolutely necessary.  Using `group_vars` would be the way to go here, and their definitions are relative to where you inventory files are stored.

1.  Lets move your variables

Move `group_vars/all.yml` to `inventory/group_vars/all/all.yml` 

End result:

```
± tree inventory
inventory
├── hosts
├── group_vars
│   ├── all
│   │   └── all.yml
```

2. Remove the `pre_tasks` as it wont be required with `group_vars` defined correctly.

Give the above a shot and report back, thanks!

**Comment by oemden** [comment]
thx for the quick answer,
I've moved the `all.yml` as proposed and I finally got it working by using `vars` declaration in the playbook roles combined with `pre_tasks`, and removed `var_files`.

If I remove/comment either one of `pre_tasks` or `vars` in the roles' declarations it fails.
I don't get the logic of the failure, but it works like this.

```
---
- name: Get Cloudflare Informations
  hosts: localhost
  # become: true
  connection: local
  # vars_files:
  #   - ../group_vars/cloudflare.yml

  pre_tasks:
  - name: set and test role variables 
    set_fact:
      cf_account_name: "{{ cf_account_name }}"
      cf_auth_token: "{{ cf_auth_token }}"

  roles:
    # Gather information about cloudflare account
    - role: linuxhq.cloudflare.account_info
      vars:
        cf_account_name: "{{ cf_account_name }}"
        cf_auth_token: "{{ cf_auth_token }}"

    # Gather information about cloudflare tunnels
    - role: linuxhq.cloudflare.tunnel_info
      vars:
        cf_account_id: "{{ _cf_account_id }}"
        cf_auth_token: "{{ _cf_auth_token }}"

    # # Gather information about cloudflare zones
    - role: linuxhq.cloudflare.zone_info
      vars:
        cf_auth_token: "{{ _cf_auth_token }}"

    # Gather information about cloudflare access applications
    - role: linuxhq.cloudflare.access_app_info
      vars:
        cf_account_id: "{{ _cf_account_id }}"
        cf_auth_token: "{{ _cf_auth_token }}"

    # Gather information about cloudflare access groups 
    - role: linuxhq.cloudflare.access_group_info
      vars:
        cf_account_id: "{{ _cf_account_id }}"
        cf_auth_token: "{{ _cf_auth_token }}"

    # Gather information about cloudflare access service tokens 
    - role: linuxhq.cloudflare.access_service_token_info
      vars:
        cf_account_id: "{{ _cf_account_id }}"
        cf_auth_token: "{{ _cf_auth_token }}"
```

As a note I'm on macOs and Ansible is installed via home-brew if it matters.

best,
O.

**Comment by tkimball83** [comment]
What does your `ansible.cfg` look like?

You shouldn't have to define `pre_tasks` or `vars` at all since they're defined in `group_vars`

When you `set_fact` its creating the same variable but in the ansible fact scope, so its redundant and not needed.

Something may be off with your ansible environment if its not picking those variables up.

**Comment by oemden** [comment]
thx for the time you provide.
I've tried even the edit you made, but I still fall back to `pre_tasks` and using `vars:` in the role to get things working.

here is the ansible.cfg
```
[defaults]
inventory = inventory
roles_path = roles
host_key_checking = False
retry_files_enabled = False
log_path = ./ansible.log
interpreter_python = /usr/bin/python3
editor = nano
# private_key_file = /some/path/tosomekey
# vault_password_file = .vault_pass

```

Also tried: to add `playbook_vars_root=top` in .cfg with `all, top,bottom` values, with no more success.

as a recap:
this does not work:
```
---
- name: Get Cloudflare Informations
  hosts: localhost
  connection: local

  # even uncommented odes not solve the roles issues.
  # pre_tasks:
  # - name: set and test role variables 
  #   set_fact:
  #     cf_account_name: "{{ cf_account_name }}"
  #     cf_auth_token: "{{ cf_auth_token }}"

  tasks:
    - name: Print variables
      debug:
        msg: 
          - "cf_account_name = {{ cf_account_name | default('NOT DEFINED') }}"
          - "cf_auth_token = {{ cf_auth_token | default('NOT DEFINED') }}"

    # Gather information about cloudflare account
    - role: linuxhq.cloudflare.account_info
      cf_account_name: "{{ cf_account_name }}"
      cf_auth_token: "{{ cf_auth_token }}"

    # Gather information about cloudflare tunnels
    - role: linuxhq.cloudflare.tunnel_info
      cf_account_id: "{{ _cf_account_id }}"
      cf_auth_token: "{{ _cf_auth_token }}"
```
and this works
```
---
- name: Get Cloudflare Informations
  hosts: localhost
  connection: local

  pre_tasks:
  - name: set and test role variables 
    set_fact:
      cf_account_name: "{{ cf_account_name }}"
      cf_auth_token: "{{ cf_auth_token }}"


  roles:
    # Gather information about cloudflare account
    - role: linuxhq.cloudflare.account_info
      vars:
        cf_account_name: "{{ cf_account_name }}"
        cf_auth_token: "{{ cf_auth_token }}"

    # Gather information about cloudflare tunnels
    - role: linuxhq.cloudflare.tunnel_info
      vars:
        cf_account_id: "{{ _cf_account_id }}"
        cf_auth_token: "{{ _cf_auth_token }}"

```
O.

I've used vars in other roles I created with no issues, yet this my first Galaxy try out... so I may do something wrong somewhere.... 
Best,
O
